import {
  type AspectRatio,
  type CanvasDocument,
  type CanvasGraph,
  DEFAULT_EXPORT,
  type EffectLayer,
  type EffectPreset,
  makeEffectPresetLayer,
  makeEmojiLayer,
  makeFillLayer,
  makeSourceLayer,
  makeTextLayer,
} from '../types/config';
import { type ArrayPresetId, makeArrayPresetLayer } from './arrayPresets';
import { makeNoisePresetLayer, type NoisePresetId } from './noisePresets';

export interface CuratedExample {
  id: string;
  name: string;
  doc: CanvasDocument;
}

function fx(preset: EffectPreset, name: string, partial: Partial<EffectLayer> = {}): EffectLayer {
  return { ...makeEffectPresetLayer(preset), name, ...partial };
}

function noise(
  preset: NoisePresetId,
  id: string,
  name: string,
  partial: Partial<ReturnType<typeof makeNoisePresetLayer>> = {},
) {
  return { ...makeNoisePresetLayer(preset), id, name, ...partial };
}

function array(
  preset: ArrayPresetId,
  id: string,
  name: string,
  partial: Partial<ReturnType<typeof makeArrayPresetLayer>> = {},
) {
  return { ...makeArrayPresetLayer(preset), id, name, ...partial };
}

function mkDoc(
  seed: number,
  bg: string,
  aspect: AspectRatio,
  layers: CanvasDocument['layers'],
  graph?: CanvasGraph,
): CanvasDocument {
  return {
    global: { bg, seed, aspect },
    export: { ...DEFAULT_EXPORT },
    layers,
    ...(graph ? { graph } : {}),
  };
}

export const CURATED_EXAMPLES: CuratedExample[] = [
  {
    id: 'static-orbit',
    name: 'Static Orbit',
    doc: mkDoc(
      24001,
      '#030307',
      '16:9',
      [
        makeFillLayer({ id: 'static-bg', name: 'void plate', color: '#030307' }),
        noise('static', 'static-snow', 'signal snow', { opacity: 85 }),
        fx('scanlines', 'crt rhythm', { id: 'static-scan', scanlines: 24, scanlineWidth: 2 }),
        array('orbitRings', 'static-orbits', 'orbit rings', { opacity: 78 }),
        fx('neonGlow', 'cyan halo', { id: 'static-neon', neonGlow: 42, neonColor: '#67ffd8' }),
        fx('vignette', 'edge pressure', { id: 'static-vignette', vignette: 58 }),
        fx('grain', 'final grit', { id: 'static-grain', grain: 24 }),
      ],
      {
        edges: [
          { id: 'e-static-bg-snow', fromId: 'static-bg', fromPort: 'out', toId: 'static-snow', toPort: 'bg' },
          { id: 'e-static-snow-scan', fromId: 'static-snow', fromPort: 'out', toId: 'static-scan', toPort: 'in' },
          { id: 'e-static-orbits-neon', fromId: 'static-orbits', fromPort: 'out', toId: 'static-neon', toPort: 'in' },
          {
            id: 'e-static-scan-merge',
            fromId: 'static-scan',
            fromPort: 'out',
            toId: 'merge-static-orbit',
            toPort: 'a',
          },
          {
            id: 'e-static-neon-merge',
            fromId: 'static-neon',
            fromPort: 'out',
            toId: 'merge-static-orbit',
            toPort: 'b',
          },
          {
            id: 'e-static-merge-vignette',
            fromId: 'merge-static-orbit',
            fromPort: 'out',
            toId: 'static-vignette',
            toPort: 'in',
          },
          {
            id: 'e-static-vignette-grain',
            fromId: 'static-vignette',
            fromPort: 'out',
            toId: 'static-grain',
            toPort: 'in',
          },
          { id: 'e-static-export', fromId: 'static-grain', fromPort: 'out', toId: '__export__', toPort: 'in' },
        ],
        positions: {
          'static-bg': { x: 0, y: 120 },
          'static-snow': { x: 360, y: 120 },
          'static-scan': { x: 720, y: 120 },
          'static-orbits': { x: 360, y: -260 },
          'static-neon': { x: 720, y: -260 },
          'merge-static-orbit': { x: 1080, y: -60 },
          'static-vignette': { x: 1440, y: -60 },
          'static-grain': { x: 1800, y: -60 },
          __export__: { x: 2160, y: -60 },
        },
        mergeNodes: [{ id: 'merge-static-orbit', name: 'orbit over signal', blendMode: 'screen', opacity: 88 }],
        colorNodes: [],
      },
    ),
  },
  {
    id: 'paper-shards',
    name: 'Paper Shards',
    doc: mkDoc(
      24002,
      '#110704',
      '4:5',
      [
        makeFillLayer({ id: 'paper-bg', name: 'warm plate', color: '#110704' }),
        noise('paper', 'paper-fiber', 'paper fiber', { opacity: 76 }),
        fx('cyanotype', 'blue print wash', { id: 'paper-cyan', cyanotype: 62 }),
        array('shardField', 'paper-shards', 'shard field', { color: '#fff4d6', accentColor: '#ff5a36', opacity: 86 }),
        fx('risoShift', 'loose registration', { id: 'paper-riso', risoShift: 16, risoAngle: 18 }),
        makeTextLayer({
          id: 'paper-title',
          name: 'caption',
          content: 'SOURCE\nFIRST',
          font: 'BEBAS',
          size: 78,
          color: '#fff7e8',
          x: 0.5,
          y: 0.58,
          scaleX: 1,
          scaleY: 1,
        }),
        fx('overprint', 'ink pressure', { id: 'paper-overprint', overprint: 28 }),
      ],
      {
        edges: [
          { id: 'e-paper-bg-fiber', fromId: 'paper-bg', fromPort: 'out', toId: 'paper-fiber', toPort: 'bg' },
          { id: 'e-paper-fiber-cyan', fromId: 'paper-fiber', fromPort: 'out', toId: 'paper-cyan', toPort: 'in' },
          { id: 'e-paper-shards-riso', fromId: 'paper-shards', fromPort: 'out', toId: 'paper-riso', toPort: 'in' },
          { id: 'e-paper-cyan-merge', fromId: 'paper-cyan', fromPort: 'out', toId: 'merge-paper-shards', toPort: 'a' },
          { id: 'e-paper-riso-merge', fromId: 'paper-riso', fromPort: 'out', toId: 'merge-paper-shards', toPort: 'b' },
          {
            id: 'e-paper-merge-title',
            fromId: 'merge-paper-shards',
            fromPort: 'out',
            toId: 'paper-title',
            toPort: 'bg',
          },
          {
            id: 'e-paper-title-overprint',
            fromId: 'paper-title',
            fromPort: 'out',
            toId: 'paper-overprint',
            toPort: 'in',
          },
          { id: 'e-paper-export', fromId: 'paper-overprint', fromPort: 'out', toId: '__export__', toPort: 'in' },
        ],
        positions: {
          'paper-bg': { x: -360, y: 120 },
          'paper-fiber': { x: 0, y: 120 },
          'paper-cyan': { x: 360, y: 120 },
          'paper-shards': { x: 0, y: -260 },
          'paper-riso': { x: 360, y: -260 },
          'merge-paper-shards': { x: 720, y: -80 },
          'paper-title': { x: 1080, y: -80 },
          'paper-overprint': { x: 1440, y: -80 },
          __export__: { x: 1800, y: -80 },
        },
        mergeNodes: [{ id: 'merge-paper-shards', name: 'paper plus shards', blendMode: 'screen', opacity: 72 }],
        colorNodes: [],
      },
    ),
  },
  {
    id: 'tower-type',
    name: 'Tower Type',
    doc: mkDoc(
      16300,
      '#050101',
      '1:1',
      [
        makeFillLayer({ id: 'tower-bg', name: 'black plate', color: '#050101' }),
        makeSourceLayer('noise', {
          id: 'tower-texture',
          name: 'concrete texture',
          color: '#250504',
          accentColor: '#9c1510',
          noiseType: 'cells',
          noiseScale: 46,
          noiseDetail: 5,
          noiseContrast: 70,
          noiseBalance: 42,
          opacity: 90,
          blendMode: 'screen',
        }),
        fx('duotone', 'red concrete', { id: 'tower-duotone', duotone: 82, duoA: '#050101', duoB: '#b32018' }),
        fx('vignette', 'stairwell falloff', { id: 'tower-vignette', vignette: 64 }),
        makeTextLayer({
          id: 'tower-title',
          name: 'title block',
          content: 'OG Buga\nFEARMUACH\n163ONMYCOCK\nHa Koprax',
          font: 'DISPLAY',
          size: 64,
          color: '#ffffff',
          x: 0.5,
          y: 0.47,
          rotation: -6,
          scaleX: 1.15,
          scaleY: 1.05,
        }),
        fx('wave', 'controlled warp', { id: 'tower-wave', waveAmt: 13, waveFreq: 2.2 }),
        fx('ca', 'white edge', { id: 'tower-ca', ca: 2 }),
        fx('scanlines', 'print lines', { id: 'tower-scan', scanlines: 8 }),
      ],
      {
        edges: [
          { id: 'e-tower-bg-texture', fromId: 'tower-bg', fromPort: 'out', toId: 'tower-texture', toPort: 'bg' },
          {
            id: 'e-tower-texture-duotone',
            fromId: 'tower-texture',
            fromPort: 'out',
            toId: 'tower-duotone',
            toPort: 'in',
          },
          {
            id: 'e-tower-duotone-vignette',
            fromId: 'tower-duotone',
            fromPort: 'out',
            toId: 'tower-vignette',
            toPort: 'in',
          },
          { id: 'e-tower-title-wave', fromId: 'tower-title', fromPort: 'out', toId: 'tower-wave', toPort: 'in' },
          { id: 'e-tower-wave-ca', fromId: 'tower-wave', fromPort: 'out', toId: 'tower-ca', toPort: 'in' },
          { id: 'e-tower-ca-scan', fromId: 'tower-ca', fromPort: 'out', toId: 'tower-scan', toPort: 'in' },
          { id: 'e-tower-bg-merge', fromId: 'tower-vignette', fromPort: 'out', toId: 'merge-tower-cover', toPort: 'a' },
          { id: 'e-tower-type-merge', fromId: 'tower-scan', fromPort: 'out', toId: 'merge-tower-cover', toPort: 'b' },
          { id: 'e-tower-export', fromId: 'merge-tower-cover', fromPort: 'out', toId: '__export__', toPort: 'in' },
        ],
        positions: {
          'tower-bg': { x: 0, y: 260 },
          'tower-texture': { x: 240, y: 260 },
          'tower-duotone': { x: 480, y: 260 },
          'tower-vignette': { x: 720, y: 260 },
          'tower-title': { x: 0, y: 0 },
          'tower-wave': { x: 240, y: 0 },
          'tower-ca': { x: 480, y: 0 },
          'tower-scan': { x: 720, y: 0 },
          'merge-tower-cover': { x: 980, y: 120 },
          __export__: { x: 1220, y: 120 },
        },
        mergeNodes: [{ id: 'merge-tower-cover', name: 'type over concrete', blendMode: 'normal', opacity: 100 }],
        colorNodes: [],
      },
    ),
  },
  {
    id: 'phantom-violet',
    name: 'Phantom Violet',
    doc: mkDoc(42069, '#0d0020', '1:1', [
      makeEmojiLayer({
        name: 'phantoms',
        emojis: ['👽', '💀', '✦', '🌀', '💜'],
        density: 32,
        minSz: 28,
        maxSz: 78,
        blur: 65,
      }),
      fx('morph', 'ghost drift', { morphAmt: 50, morphFreq: 7 }),
      fx('noiseWarp', 'signal bend', { noiseWarp: 30 }),
      fx('rays', 'violet rays', { rays: 18, rayInt: 68, rayColor: '#9900ff' }),
      fx('tint', 'violet wash', { tint: '#1a0035', tintOp: 25 }),
      fx('grain', 'dust', { grain: 25 }),
      fx('scanlines', 'scan', { scanlines: 15 }),
      fx('rgbSplit', 'split', { rgbSplit: 4 }),
      fx('vignette', 'falloff', { vignette: 40 }),
      fx('bloom', 'glow', { bloom: 25 }),
    ]),
  },
  {
    id: 'glitch-tape',
    name: 'Glitch Tape',
    doc: mkDoc(13370, '#001008', '16:9', [
      makeEmojiLayer({
        name: 'tape debris',
        emojis: ['📼', '🔴', '⚡', '💾', '🖥️'],
        density: 28,
        minSz: 20,
        maxSz: 90,
        blur: 50,
      }),
      fx('glitch', 'dropout', { glitch: 15 }),
      fx('tear', 'tracking tear', { tearAmt: 12, tearSize: 5 }),
      fx('dataMosh', 'mosh', { dataMosh: 60 }),
      fx('interlace', 'crt weave', { interlace: 40 }),
      fx('hueShift', 'green drift', { hueShift: 120 }),
      fx('rgbSplit', 'channel split', { rgbSplit: 18 }),
      fx('grain', 'video noise', { grain: 35 }),
      fx('scanlines', 'scan', { scanlines: 25 }),
      fx('tint', 'phosphor wash', { tint: '#002210', tintOp: 20 }),
      fx('vignette', 'frame darken', { vignette: 55 }),
      fx('bloom', 'tube bloom', { bloom: 35 }),
    ]),
  },
  {
    id: 'vortex-dream',
    name: 'Vortex Dream',
    doc: mkDoc(77777, '#000820', '9:16', [
      makeEmojiLayer({
        name: 'orbitals',
        emojis: ['🌀', '🫧', '⭕', '💫', '🔵'],
        density: 45,
        minSz: 15,
        maxSz: 65,
        blur: 72,
      }),
      fx('noiseWarp', 'current', { noiseWarp: 20 }),
      fx('vortex', 'pull', { vortex: 80 }),
      fx('barrel', 'lens warp', { barrel: 60 }),
      fx('rays', 'blue rays', { rays: 24, rayInt: 55, rayColor: '#0066ff' }),
      fx('tint', 'blue wash', { tint: '#00082a', tintOp: 35 }),
      fx('hueShift', 'deep hue', { hueShift: 200 }),
      fx('rgbSplit', 'fringe', { rgbSplit: 7 }),
      fx('rgbSplit', 'split', { rgbSplit: 8 }),
      fx('vignette', 'falloff', { vignette: 65 }),
      fx('bloom', 'halo', { bloom: 55 }),
    ]),
  },
  {
    id: 'film-ghost',
    name: 'Film Ghost',
    doc: mkDoc(9876, '#140800', '4:5', [
      makeEmojiLayer({
        name: 'apparitions',
        emojis: ['🎞️', '👻', '🌫️', '✨', '🕯️'],
        density: 25,
        minSz: 40,
        maxSz: 100,
        blur: 80,
      }),
      fx('filmBurn', 'light leak', { filmBurn: 80 }),
      fx('noiseWarp', 'heat warp', { noiseWarp: 70 }),
      fx('barrel', 'soft warp', { barrel: 25 }),
      fx('rays', 'lamp flare', { rays: 6, rayInt: 40, rayColor: '#ff6600' }),
      fx('tint', 'amber wash', { tint: '#200a00', tintOp: 40 }),
      fx('grain', 'stock grain', { grain: 45 }),
      fx('interlace', 'aged scan', { interlace: 20 }),
      fx('vignette', 'fade', { vignette: 75 }),
      fx('bloom', 'soft bloom', { bloom: 45 }),
    ]),
  },
  {
    id: 'riso-print',
    name: 'Riso Print',
    doc: mkDoc(31415, '#1a0010', '1:1', [
      makeEmojiLayer({
        name: 'petals',
        emojis: ['🌸', '📿', '🌺', '💌', '🎀'],
        density: 40,
        minSz: 25,
        maxSz: 75,
        blur: 45,
      }),
      fx('rays', 'pink flash', { rays: 12, rayInt: 60, rayColor: '#ff0080' }),
      fx('hueShift', 'ink hue', { hueShift: 310 }),
      fx('duotone', 'duo ink', { duotone: 70, duoA: '#0a001a', duoB: '#ff44cc' }),
      fx('posterize', 'plate bands', { posterize: 8 }),
      fx('halftone', 'screen dots', { halftone: 15 }),
      fx('risoShift', 'misregister', { risoShift: 25, risoAngle: 220 }),
      fx('grain', 'paper tooth', { grain: 30 }),
      fx('rgbSplit', 'registration split', { rgbSplit: 6 }),
      fx('vignette', 'edge fade', { vignette: 35 }),
      fx('bloom', 'ink glow', { bloom: 20 }),
    ]),
  },
  {
    id: 'acid-rain',
    name: 'Acid Rain',
    doc: mkDoc(55555, '#0a1000', '16:9', [
      makeEmojiLayer({
        name: 'acid drops',
        emojis: ['☠️', '🧪', '💚', '⚗️', '🌿'],
        density: 38,
        minSz: 22,
        maxSz: 80,
        blur: 60,
      }),
      fx('glitch', 'dropout', { glitch: 10 }),
      fx('noiseWarp', 'corrosion warp', { noiseWarp: 40 }),
      fx('barrel', 'lens warp', { barrel: 30 }),
      fx('dataMosh', 'green smear', { dataMosh: 20 }),
      fx('rays', 'toxic rays', { rays: 16, rayInt: 52, rayColor: '#aaff00' }),
      fx('tint', 'sludge wash', { tint: '#091200', tintOp: 30 }),
      fx('hueShift', 'acid hue', { hueShift: 90 }),
      fx('rgbSplit', 'fringe', { rgbSplit: 6 }),
      fx('grain', 'grit', { grain: 28 }),
      fx('scanlines', 'signal rain', { scanlines: 18 }),
      fx('rgbSplit', 'channel bleed', { rgbSplit: 10 }),
      fx('vignette', 'edge rot', { vignette: 60 }),
      fx('bloom', 'neon spill', { bloom: 70 }),
    ]),
  },
  {
    id: 'void-echo',
    name: 'Void Echo',
    doc: mkDoc(11111, '#04000a', '9:16', [
      makeEmojiLayer({
        name: 'eclipses',
        emojis: ['🌑', '🌘', '⚫', '🖤', '🌙'],
        density: 50,
        minSz: 18,
        maxSz: 60,
        blur: 85,
      }),
      fx('mirror', 'echo mirror', { mirror: 2 }),
      fx('morph', 'slow drift', { morphAmt: 60, morphFreq: 4 }),
      fx('vortex', 'void pull', { vortex: 40 }),
      fx('rays', 'eclipse rays', { rays: 30, rayInt: 30, rayColor: '#6600aa' }),
      fx('tint', 'night wash', { tint: '#080010', tintOp: 50 }),
      fx('duotone', 'moon duo', { duotone: 30, duoA: '#02000a', duoB: '#8833ff' }),
      fx('interlace', 'echo lines', { interlace: 30 }),
      fx('hueShift', 'violet drift', { hueShift: 270 }),
      fx('grain', 'dust', { grain: 15 }),
      fx('rgbSplit', 'trace split', { rgbSplit: 2 }),
      fx('vignette', 'heavy falloff', { vignette: 85 }),
      fx('bloom', 'lunar bloom', { bloom: 60 }),
    ]),
  },
  {
    id: 'pixel-death',
    name: 'Pixel Death',
    doc: mkDoc(66666, '#200000', '4:5', [
      makeEmojiLayer({
        name: 'wreckage',
        emojis: ['💀', '🔥', '⚡', '🩸', '☠️'],
        density: 35,
        minSz: 30,
        maxSz: 85,
        blur: 40,
      }),
      fx('tear', 'hard tear', { tearAmt: 8, tearSize: 4 }),
      fx('dataMosh', 'mosh', { dataMosh: 40 }),
      fx('interlace', 'shred', { interlace: 60 }),
      fx('pixelate', 'block crush', { pixelate: 8 }),
      fx('posterize', 'reduced bands', { posterize: 6 }),
      fx('duotone', 'blood duo', { duotone: 50, duoA: '#1a0000', duoB: '#ff4400' }),
      fx('rays', 'red spike', { rays: 10, rayInt: 70, rayColor: '#ff2200' }),
      fx('grain', 'grit', { grain: 40 }),
      fx('scanlines', 'scan', { scanlines: 30 }),
      fx('rgbSplit', 'fringe', { rgbSplit: 8 }),
      fx('rgbSplit', 'channel rip', { rgbSplit: 14 }),
      fx('vignette', 'edge crush', { vignette: 70 }),
      fx('bloom', 'burn', { bloom: 30 }),
    ]),
  },
];
