import {
  type AspectRatio,
  type CanvasDocument,
  DEFAULT_EXPORT,
  type EffectLayer,
  type EffectPreset,
  makeEffectPresetLayer,
  makeEmojiLayer,
} from '../types/config';

export interface CuratedExample {
  id: string;
  name: string;
  doc: CanvasDocument;
}

function fx(preset: EffectPreset, name: string, partial: Partial<EffectLayer> = {}): EffectLayer {
  return { ...makeEffectPresetLayer(preset), name, ...partial };
}

function mkDoc(seed: number, bg: string, aspect: AspectRatio, layers: CanvasDocument['layers']): CanvasDocument {
  return {
    global: { bg, seed, aspect },
    export: { ...DEFAULT_EXPORT },
    layers,
  };
}

export const CURATED_EXAMPLES: CuratedExample[] = [
  {
    id: 'phantom-violet',
    name: 'Phantom Violet',
    doc: mkDoc(42069, '#0d0020', '1:1', [
      makeEmojiLayer({
        name: 'phantoms',
        emojis: ['👽', '💀', '✦', '🌀', '💜'],
        density: 32,
        minSz: 28,
        maxSz: 78,
        blur: 65,
      }),
      fx('morph', 'ghost drift', { morphAmt: 50, morphFreq: 7 }),
      fx('noiseWarp', 'signal bend', { noiseWarp: 30 }),
      fx('rays', 'violet rays', { rays: 18, rayInt: 68, rayColor: '#9900ff' }),
      fx('tint', 'violet wash', { tint: '#1a0035', tintOp: 25 }),
      fx('grain', 'dust', { grain: 25 }),
      fx('scanlines', 'scan', { scanlines: 15 }),
      fx('rgbSplit', 'split', { rgbSplit: 4 }),
      fx('vignette', 'falloff', { vignette: 40 }),
      fx('bloom', 'glow', { bloom: 25 }),
    ]),
  },
  {
    id: 'glitch-tape',
    name: 'Glitch Tape',
    doc: mkDoc(13370, '#001008', '16:9', [
      makeEmojiLayer({
        name: 'tape debris',
        emojis: ['📼', '🔴', '⚡', '💾', '🖥️'],
        density: 28,
        minSz: 20,
        maxSz: 90,
        blur: 50,
      }),
      fx('glitch', 'dropout', { glitch: 15 }),
      fx('tear', 'tracking tear', { tearAmt: 12, tearSize: 5 }),
      fx('dataMosh', 'mosh', { dataMosh: 60 }),
      fx('interlace', 'crt weave', { interlace: 40 }),
      fx('hueShift', 'green drift', { hueShift: 120 }),
      fx('rgbSplit', 'channel split', { rgbSplit: 18 }),
      fx('grain', 'video noise', { grain: 35 }),
      fx('scanlines', 'scan', { scanlines: 25 }),
      fx('tint', 'phosphor wash', { tint: '#002210', tintOp: 20 }),
      fx('vignette', 'frame darken', { vignette: 55 }),
      fx('bloom', 'tube bloom', { bloom: 35 }),
    ]),
  },
  {
    id: 'vortex-dream',
    name: 'Vortex Dream',
    doc: mkDoc(77777, '#000820', '9:16', [
      makeEmojiLayer({
        name: 'orbitals',
        emojis: ['🌀', '🫧', '⭕', '💫', '🔵'],
        density: 45,
        minSz: 15,
        maxSz: 65,
        blur: 72,
      }),
      fx('noiseWarp', 'current', { noiseWarp: 20 }),
      fx('vortex', 'pull', { vortex: 80 }),
      fx('barrel', 'lens warp', { barrel: 60 }),
      fx('rays', 'blue rays', { rays: 24, rayInt: 55, rayColor: '#0066ff' }),
      fx('tint', 'blue wash', { tint: '#00082a', tintOp: 35 }),
      fx('hueShift', 'deep hue', { hueShift: 200 }),
      fx('rgbSplit', 'fringe', { rgbSplit: 7 }),
      fx('rgbSplit', 'split', { rgbSplit: 8 }),
      fx('vignette', 'falloff', { vignette: 65 }),
      fx('bloom', 'halo', { bloom: 55 }),
    ]),
  },
  {
    id: 'film-ghost',
    name: 'Film Ghost',
    doc: mkDoc(9876, '#140800', '4:5', [
      makeEmojiLayer({
        name: 'apparitions',
        emojis: ['🎞️', '👻', '🌫️', '✨', '🕯️'],
        density: 25,
        minSz: 40,
        maxSz: 100,
        blur: 80,
      }),
      fx('filmBurn', 'light leak', { filmBurn: 80 }),
      fx('noiseWarp', 'heat warp', { noiseWarp: 70 }),
      fx('barrel', 'soft warp', { barrel: 25 }),
      fx('rays', 'lamp flare', { rays: 6, rayInt: 40, rayColor: '#ff6600' }),
      fx('tint', 'amber wash', { tint: '#200a00', tintOp: 40 }),
      fx('grain', 'stock grain', { grain: 45 }),
      fx('interlace', 'aged scan', { interlace: 20 }),
      fx('vignette', 'fade', { vignette: 75 }),
      fx('bloom', 'soft bloom', { bloom: 45 }),
    ]),
  },
  {
    id: 'riso-print',
    name: 'Riso Print',
    doc: mkDoc(31415, '#1a0010', '1:1', [
      makeEmojiLayer({
        name: 'petals',
        emojis: ['🌸', '📿', '🌺', '💌', '🎀'],
        density: 40,
        minSz: 25,
        maxSz: 75,
        blur: 45,
      }),
      fx('rays', 'pink flash', { rays: 12, rayInt: 60, rayColor: '#ff0080' }),
      fx('hueShift', 'ink hue', { hueShift: 310 }),
      fx('duotone', 'duo ink', { duotone: 70, duoA: '#0a001a', duoB: '#ff44cc' }),
      fx('posterize', 'plate bands', { posterize: 8 }),
      fx('halftone', 'screen dots', { halftone: 15 }),
      fx('risoShift', 'misregister', { risoShift: 25, risoAngle: 220 }),
      fx('grain', 'paper tooth', { grain: 30 }),
      fx('rgbSplit', 'registration split', { rgbSplit: 6 }),
      fx('vignette', 'edge fade', { vignette: 35 }),
      fx('bloom', 'ink glow', { bloom: 20 }),
    ]),
  },
  {
    id: 'acid-rain',
    name: 'Acid Rain',
    doc: mkDoc(55555, '#0a1000', '16:9', [
      makeEmojiLayer({
        name: 'acid drops',
        emojis: ['☠️', '🧪', '💚', '⚗️', '🌿'],
        density: 38,
        minSz: 22,
        maxSz: 80,
        blur: 60,
      }),
      fx('glitch', 'dropout', { glitch: 10 }),
      fx('noiseWarp', 'corrosion warp', { noiseWarp: 40 }),
      fx('barrel', 'lens warp', { barrel: 30 }),
      fx('dataMosh', 'green smear', { dataMosh: 20 }),
      fx('rays', 'toxic rays', { rays: 16, rayInt: 52, rayColor: '#aaff00' }),
      fx('tint', 'sludge wash', { tint: '#091200', tintOp: 30 }),
      fx('hueShift', 'acid hue', { hueShift: 90 }),
      fx('rgbSplit', 'fringe', { rgbSplit: 6 }),
      fx('grain', 'grit', { grain: 28 }),
      fx('scanlines', 'signal rain', { scanlines: 18 }),
      fx('rgbSplit', 'channel bleed', { rgbSplit: 10 }),
      fx('vignette', 'edge rot', { vignette: 60 }),
      fx('bloom', 'neon spill', { bloom: 70 }),
    ]),
  },
  {
    id: 'void-echo',
    name: 'Void Echo',
    doc: mkDoc(11111, '#04000a', '9:16', [
      makeEmojiLayer({
        name: 'eclipses',
        emojis: ['🌑', '🌘', '⚫', '🖤', '🌙'],
        density: 50,
        minSz: 18,
        maxSz: 60,
        blur: 85,
      }),
      fx('mirror', 'echo mirror', { mirror: 2 }),
      fx('morph', 'slow drift', { morphAmt: 60, morphFreq: 4 }),
      fx('vortex', 'void pull', { vortex: 40 }),
      fx('rays', 'eclipse rays', { rays: 30, rayInt: 30, rayColor: '#6600aa' }),
      fx('tint', 'night wash', { tint: '#080010', tintOp: 50 }),
      fx('duotone', 'moon duo', { duotone: 30, duoA: '#02000a', duoB: '#8833ff' }),
      fx('interlace', 'echo lines', { interlace: 30 }),
      fx('hueShift', 'violet drift', { hueShift: 270 }),
      fx('grain', 'dust', { grain: 15 }),
      fx('rgbSplit', 'trace split', { rgbSplit: 2 }),
      fx('vignette', 'heavy falloff', { vignette: 85 }),
      fx('bloom', 'lunar bloom', { bloom: 60 }),
    ]),
  },
  {
    id: 'pixel-death',
    name: 'Pixel Death',
    doc: mkDoc(66666, '#200000', '4:5', [
      makeEmojiLayer({
        name: 'wreckage',
        emojis: ['💀', '🔥', '⚡', '🩸', '☠️'],
        density: 35,
        minSz: 30,
        maxSz: 85,
        blur: 40,
      }),
      fx('tear', 'hard tear', { tearAmt: 8, tearSize: 4 }),
      fx('dataMosh', 'mosh', { dataMosh: 40 }),
      fx('interlace', 'shred', { interlace: 60 }),
      fx('pixelate', 'block crush', { pixelate: 8 }),
      fx('posterize', 'reduced bands', { posterize: 6 }),
      fx('duotone', 'blood duo', { duotone: 50, duoA: '#1a0000', duoB: '#ff4400' }),
      fx('rays', 'red spike', { rays: 10, rayInt: 70, rayColor: '#ff2200' }),
      fx('grain', 'grit', { grain: 40 }),
      fx('scanlines', 'scan', { scanlines: 30 }),
      fx('rgbSplit', 'fringe', { rgbSplit: 8 }),
      fx('rgbSplit', 'channel rip', { rgbSplit: 14 }),
      fx('vignette', 'edge crush', { vignette: 70 }),
      fx('bloom', 'burn', { bloom: 30 }),
    ]),
  },
];
