import type { ReactNode } from 'react';
import { Field, Input, NativeSelect, Textarea } from './fields';
import type { FieldFoundationSpecimenId } from './foundation-field-specimens';

export function FoundationFieldMatrix() {
  return (
    <div className="ui-foundation-matrix" data-foundation-section="fields" aria-label="UI Foundation field matrix">
      <FieldSpecimen id="input-default" label="Input / default">
        <Field label="Project title" hint="Shown in the project list.">
          <Input defaultValue="Night Transit" />
        </Field>
      </FieldSpecimen>
      <FieldSpecimen id="input-focus" label="Input / keyboard focus">
        <Field label="Artist">
          <Input defaultValue="Signal Choir" />
        </Field>
      </FieldSpecimen>
      <FieldSpecimen id="input-error" label="Input / error">
        <Field label="Release title" error="Enter a release title.">
          <Input />
        </Field>
      </FieldSpecimen>
      <FieldSpecimen id="input-disabled" label="Input / disabled">
        <Field label="Published slug">
          <Input defaultValue="night-transit" disabled />
        </Field>
      </FieldSpecimen>
      <FieldSpecimen id="input-readonly" label="Input / readonly">
        <Field label="Document ID" hint="Generated by Artifact.">
          <Input value="ART-042" readOnly />
        </Field>
      </FieldSpecimen>
      <FieldSpecimen id="textarea-default" label="Textarea / default">
        <Field label="Creative note" hint="Keep the direction concise.">
          <Textarea defaultValue="Warm type over a cool photographic field." rows={3} />
        </Field>
      </FieldSpecimen>
      <FieldSpecimen id="textarea-error" label="Textarea / error">
        <Field label="Generation prompt" error="Describe the intended result.">
          <Textarea rows={3} />
        </Field>
      </FieldSpecimen>
      <FieldSpecimen id="textarea-disabled" label="Textarea / disabled">
        <Field label="Archived note">
          <Textarea defaultValue="This note is unavailable." disabled rows={3} />
        </Field>
      </FieldSpecimen>
      <FieldSpecimen id="textarea-readonly" label="Textarea / readonly">
        <Field label="Source summary">
          <Textarea value="Imported from the project document." readOnly rows={3} />
        </Field>
      </FieldSpecimen>
      <FieldSpecimen id="native-select-default" label="NativeSelect / default">
        <Field label="Export format" hint="Choose a browser-native option.">
          <NativeSelect defaultValue="png">
            <option value="png">PNG</option>
            <option value="jpeg">JPEG</option>
          </NativeSelect>
        </Field>
      </FieldSpecimen>
      <FieldSpecimen id="native-select-error" label="NativeSelect / error">
        <Field label="Aspect ratio" error="Choose an aspect ratio.">
          <NativeSelect defaultValue="">
            <option value="">Select ratio</option>
            <option value="square">Square</option>
          </NativeSelect>
        </Field>
      </FieldSpecimen>
      <FieldSpecimen id="native-select-disabled" label="NativeSelect / disabled">
        <Field label="Color profile">
          <NativeSelect defaultValue="srgb" disabled>
            <option value="srgb">sRGB</option>
          </NativeSelect>
        </Field>
      </FieldSpecimen>
    </div>
  );
}

function FieldSpecimen({ children, id, label }: { children: ReactNode; id: FieldFoundationSpecimenId; label: string }) {
  return (
    <div className="ui-foundation-specimen ui-foundation-specimen--field" data-foundation-specimen={id}>
      <span className="ui-foundation-specimen__label">{label}</span>
      <div className="ui-foundation-specimen__control">{children}</div>
    </div>
  );
}
