export type {
  AiAccessResponse,
  AiErrorResponse,
  AiGenerationAssetResponse,
  AiGenerationJobResponse,
  AiGenerationSettings,
  AiProvider,
  AiQuotaSnapshot,
  AiShaderGenerationResponse,
  AiShaderRequestMode,
  AiShaderSource,
  ApiHealthResponse,
  CreateAiShaderRequest,
  CreateGenerationRequest,
  GenerationQueuePayload,
  ShaderDefinition,
  ShaderInstance,
  ShaderPropertyDefinition,
} from '@artifact/shared';

export {
  AI_API_PATHS,
  AI_PROVIDERS,
  AI_SHADER_PROMPT_MAX_LENGTH,
  normalizeShaderDefinition,
  normalizeShaderInstance,
  stripShaderCodeComments,
  validateShaderCode,
  validateShaderDefinition,
  validateShaderInstance,
} from '@artifact/shared';
