import { randomUUID } from 'node:crypto';
import type { AiGenerationSettings, AiProvider, GenerationQueuePayload } from './contracts.js';
import type { ApiRepositories } from './db/repositories.js';
import type { AiGenerationJobRow, JsonObject, JsonValue } from './db/types.js';
import type { ImageGenerationResult, ProviderRegistry } from './providers/index.js';
import type { QueueJob } from './queue.js';
import type { AssetStorage } from './storage/index.js';

export interface GenerationWorkerDeps {
  repositories: ApiRepositories;
  providers: ProviderRegistry;
  storage: AssetStorage;
  now?: () => Date;
  createId?: () => string;
}

export async function processGenerationJob(
  queueJob: QueueJob<GenerationQueuePayload>,
  deps: GenerationWorkerDeps,
): Promise<void> {
  const job = await deps.repositories.jobs.findByIdForUser(queueJob.data.jobId, queueJob.data.userId);
  if (!job || job.status !== 'queued') return;

  try {
    const running = await deps.repositories.jobs.markRunning(job.id, deps.now?.() ?? new Date());
    const provider = deps.providers.get(running.provider as AiProvider);
    const result = await provider.generateImage({
      jobId: running.id,
      userId: running.user_id,
      provider: provider.provider,
      model: running.model,
      prompt: running.prompt,
      settings: running.settings_json as unknown as AiGenerationSettings,
    });
    const assetId = deps.createId?.() ?? randomUUID();
    const stored = await deps.storage.writeImage({
      assetId,
      bytes: result.bytes,
      mimeType: result.mimeType,
    });
    const completedAt = deps.now?.() ?? new Date();

    await deps.repositories.assets.create({
      id: assetId,
      userId: running.user_id,
      kind: 'generated-image',
      storageKey: stored.storageKey,
      mimeType: stored.mimeType,
      width: result.width,
      height: result.height,
      sizeBytes: stored.sizeBytes,
      metadataJson: createGeneratedAssetMetadata(running, result, completedAt),
    });
    await deps.repositories.jobs.markSucceeded(running.id, assetId, completedAt);
  } catch (error) {
    await deps.repositories.jobs.markFailed(job.id, {
      code: 'provider_error',
      message: error instanceof Error ? error.message : 'Image generation failed.',
      retryable: true,
      providerUsageJson: null,
      estimatedCost: null,
    });
  }
}

function createGeneratedAssetMetadata(
  job: AiGenerationJobRow,
  result: ImageGenerationResult,
  createdAt: Date,
): JsonObject {
  const metadata: JsonObject = {
    provider: job.provider,
    model: job.model,
    prompt: job.prompt,
    negativePrompt: job.negative_prompt,
    settings: job.settings_json,
    providerUsage: toJsonObject(result.usage?.metadata),
    licenseNote: 'Generated by the configured private Artifact provider adapter.',
    createdAt: createdAt.toISOString(),
  };
  if (result.usage?.estimatedCostUsd !== undefined) metadata.estimatedCostUsd = result.usage.estimatedCostUsd;
  return metadata;
}

function toJsonObject(value: Record<string, unknown> | undefined): JsonObject | null {
  if (!value) return null;
  return Object.fromEntries(
    Object.entries(value)
      .map(([key, item]) => [key, toJsonValue(item)] as const)
      .filter((entry): entry is readonly [string, JsonValue] => entry[1] !== undefined),
  );
}

function toJsonValue(value: unknown): JsonValue | undefined {
  if (value === null || typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') {
    return value;
  }
  if (Array.isArray(value)) {
    return value.map(toJsonValue).filter((item): item is JsonValue => item !== undefined);
  }
  if (typeof value === 'object') {
    return toJsonObject(value as Record<string, unknown>) ?? {};
  }
  return undefined;
}
