import {
  type AspectRatio,
  type CanvasDocument,
  type CanvasGraph,
  DEFAULT_EXPORT,
  type EffectLayer,
  type EffectPreset,
  makeEffectPresetLayer,
  makeEmojiLayer,
  makeFillLayer,
  makeSourceLayer,
  makeTextLayer,
} from '../types/config';
import { type ArrayPresetId, makeArrayPresetLayer } from './arrayPresets';
import { makeNoisePresetLayer, type NoisePresetId } from './noisePresets';
import {
  MASKED_TYPE_LINES_GRAPH_RECIPE,
  MULTI_FONT_TYPE_STACK_STARTER,
  NOISE_MATTE_MERGE_GRAPH_RECIPE,
  NOISE_POSTER_STACK_STARTER,
  PHOTO_TYPE_GRAPH_RECIPE,
  PHOTO_TYPE_STACK_STARTER,
  PRIMITIVE_IMAGE_GRAPH_RECIPE,
  PRINT_DAMAGE_GRAPH_RECIPE,
  ROTATED_CIRCLE_TOKENS_GRAPH_RECIPE,
  STICKER_GRID_GRAPH_RECIPE,
  type StarterDocument,
  TEXTURE_TYPE_STACK_STARTER,
  WARPED_LINE_POSTER_GRAPH_RECIPE,
} from './starterDocuments';

export type CuratedExampleCategory = 'Layer recipe' | 'Graph recipe' | 'Texture study' | 'Effect stack';

export interface CuratedExample {
  id: string;
  name: string;
  category: CuratedExampleCategory;
  summary: string;
  usedNodes: string[];
  startCopy: string;
  doc: CanvasDocument;
}

function fx(preset: EffectPreset, name: string, partial: Partial<EffectLayer> = {}): EffectLayer {
  return { ...makeEffectPresetLayer(preset), name, ...partial };
}

function noise(
  preset: NoisePresetId,
  id: string,
  name: string,
  partial: Partial<ReturnType<typeof makeNoisePresetLayer>> = {},
) {
  return { ...makeNoisePresetLayer(preset), id, name, ...partial };
}

function array(
  preset: ArrayPresetId,
  id: string,
  name: string,
  partial: Partial<ReturnType<typeof makeArrayPresetLayer>> = {},
) {
  return { ...makeArrayPresetLayer(preset), id, name, ...partial };
}

function mkDoc(
  seed: number,
  bg: string,
  aspect: AspectRatio,
  layers: CanvasDocument['layers'],
  graph?: CanvasGraph,
): CanvasDocument {
  return {
    global: { bg, seed, aspect },
    export: { ...DEFAULT_EXPORT },
    layers,
    ...(graph ? { graph } : {}),
  };
}

function starterExample(
  starter: StarterDocument,
  metadata: Pick<CuratedExample, 'category' | 'summary' | 'usedNodes' | 'startCopy'>,
): CuratedExample {
  return {
    id: starter.id,
    name: starter.name,
    doc: starter.doc,
    ...metadata,
  };
}

export const CURATED_EXAMPLES: CuratedExample[] = [
  starterExample(MULTI_FONT_TYPE_STACK_STARTER, {
    category: 'Layer recipe',
    summary: 'A text-first stack for mixing poster, mono, pixel, and typewriter fonts with a print finish.',
    usedNodes: ['Fill', 'Image', 'Noise', 'Text', 'Riso Shift', 'Grain'],
    startCopy: 'Open this to swap the words, audition fonts, and keep the whole cover in layer mode.',
  }),
  starterExample(TEXTURE_TYPE_STACK_STARTER, {
    category: 'Layer recipe',
    summary: 'Build a stack-only cover from fill, procedural texture, display type, and print effects.',
    usedNodes: ['Fill', 'Noise', 'Text', 'Riso Shift', 'Scanlines', 'Grain'],
    startCopy: 'Start with this layer stack and swap the title, colors, or texture seed.',
  }),
  starterExample(PHOTO_TYPE_STACK_STARTER, {
    category: 'Layer recipe',
    summary: 'A photo-first stack that keeps replacement image, color wash, type, and print grain in layer order.',
    usedNodes: ['Fill', 'Image', 'Duotone', 'Text', 'Riso Shift', 'Grain'],
    startCopy: 'Open this when you want to replace the photo, rewrite the title, and export without touching nodes.',
  }),
  starterExample(NOISE_POSTER_STACK_STARTER, {
    category: 'Layer recipe',
    summary: 'A type poster built from procedural paper static, oversized text, halftone, scanlines, and dust.',
    usedNodes: ['Fill', 'Noise', 'Text', 'Halftone', 'Scanlines', 'Grain'],
    startCopy: 'Use this for quick poster studies where texture and type are enough to finish the cover.',
  }),
  starterExample(PHOTO_TYPE_GRAPH_RECIPE, {
    category: 'Graph recipe',
    summary: 'A photo-led graph where image tone, title placement, and final grain stay as separate editable steps.',
    usedNodes: ['Fill', 'Image', 'Duotone', 'Text', 'Grain', 'Output'],
    startCopy: 'Open this when you want to replace the image first, then tune type and color.',
  }),
  starterExample(STICKER_GRID_GRAPH_RECIPE, {
    category: 'Graph recipe',
    summary: 'A motif-grid workflow with paper texture, array shapes, registration drift, and label type.',
    usedNodes: ['Fill', 'Noise', 'Array', 'Riso Shift', 'Text', 'Overprint'],
    startCopy: 'Use this for sticker sheets, repeated marks, and grid-based cover systems.',
  }),
  starterExample(PRIMITIVE_IMAGE_GRAPH_RECIPE, {
    category: 'Graph recipe',
    summary: 'Two branches merge a 3D primitive over an image wash before type and vignette finishing.',
    usedNodes: ['Image', 'Primitive', 'Neon Glow', 'Merge', 'Text', 'Vignette'],
    startCopy: 'Start here to practice keeping an object branch separate from the image branch.',
  }),
  starterExample(PRINT_DAMAGE_GRAPH_RECIPE, {
    category: 'Graph recipe',
    summary: 'A poster workflow that pushes type through paper fiber, halftone, tears, and dust.',
    usedNodes: ['Fill', 'Noise', 'Text', 'Halftone', 'Tear', 'Grain'],
    startCopy: 'Open this for distressed posters where every damage pass remains editable.',
  }),
  starterExample(MASKED_TYPE_LINES_GRAPH_RECIPE, {
    category: 'Graph recipe',
    summary: 'Diagonal line material is clipped by editable type before it is merged over a dark plate.',
    usedNodes: ['Fill', 'Line Field', 'Text', 'Mask', 'Merge', 'Grain'],
    startCopy: 'Open this to learn the Mask node with type as the matte and line work as the source.',
  }),
  starterExample(ROTATED_CIRCLE_TOKENS_GRAPH_RECIPE, {
    category: 'Graph recipe',
    summary: 'A circular mask creates a token, then Repeat rotates each copy into a radial mark system.',
    usedNodes: ['Fill', 'Line Field', 'Array', 'Mask', 'Repeat', 'Text'],
    startCopy: 'Use this when each repeated copy should keep the same shape but get its own internal angle.',
  }),
  starterExample(WARPED_LINE_POSTER_GRAPH_RECIPE, {
    category: 'Graph recipe',
    summary: 'A bulged procedural line source becomes the main poster material behind editable type.',
    usedNodes: ['Fill', 'Line Field', 'Text', 'Scanlines', 'Output'],
    startCopy: 'Open this to tune line count, stroke, distortion strength, and frequency in one source node.',
  }),
  starterExample(NOISE_MATTE_MERGE_GRAPH_RECIPE, {
    category: 'Graph recipe',
    summary: 'A noisy matte controls where a line texture branch appears before type is added.',
    usedNodes: ['Fill', 'Line Field', 'Noise', 'Mask', 'Merge', 'Text'],
    startCopy: 'Use this for smart masked merges where the matte remains editable instead of flattened.',
  }),
  {
    id: 'static-orbit',
    name: 'Static Orbit',
    category: 'Texture study',
    summary: 'Signal snow and orbit rings stay on separate branches before a screen merge and final grit.',
    usedNodes: ['Fill', 'Noise', 'Array', 'Scanlines', 'Neon Glow', 'Merge'],
    startCopy: 'Remix this to learn graph branches, screen blends, and procedural source variation.',
    doc: mkDoc(
      24001,
      '#030307',
      '16:9',
      [
        makeFillLayer({ id: 'static-bg', name: 'void plate', color: '#030307' }),
        noise('static', 'static-snow', 'signal snow', { opacity: 85 }),
        fx('scanlines', 'crt rhythm', { id: 'static-scan', scanlines: 24, scanlineWidth: 2 }),
        array('orbitRings', 'static-orbits', 'orbit rings', { opacity: 78 }),
        fx('neonGlow', 'cyan halo', { id: 'static-neon', neonGlow: 42, neonColor: '#67ffd8' }),
        fx('vignette', 'edge pressure', { id: 'static-vignette', vignette: 58 }),
        fx('grain', 'final grit', { id: 'static-grain', grain: 24 }),
      ],
      {
        edges: [
          { id: 'e-static-bg-snow', fromId: 'static-bg', fromPort: 'out', toId: 'static-snow', toPort: 'bg' },
          { id: 'e-static-snow-scan', fromId: 'static-snow', fromPort: 'out', toId: 'static-scan', toPort: 'in' },
          { id: 'e-static-orbits-neon', fromId: 'static-orbits', fromPort: 'out', toId: 'static-neon', toPort: 'in' },
          {
            id: 'e-static-scan-merge',
            fromId: 'static-scan',
            fromPort: 'out',
            toId: 'merge-static-orbit',
            toPort: 'a',
          },
          {
            id: 'e-static-neon-merge',
            fromId: 'static-neon',
            fromPort: 'out',
            toId: 'merge-static-orbit',
            toPort: 'b',
          },
          {
            id: 'e-static-merge-vignette',
            fromId: 'merge-static-orbit',
            fromPort: 'out',
            toId: 'static-vignette',
            toPort: 'in',
          },
          {
            id: 'e-static-vignette-grain',
            fromId: 'static-vignette',
            fromPort: 'out',
            toId: 'static-grain',
            toPort: 'in',
          },
          { id: 'e-static-export', fromId: 'static-grain', fromPort: 'out', toId: '__export__', toPort: 'in' },
        ],
        positions: {
          'static-bg': { x: 0, y: 120 },
          'static-snow': { x: 360, y: 120 },
          'static-scan': { x: 720, y: 120 },
          'static-orbits': { x: 360, y: -260 },
          'static-neon': { x: 720, y: -260 },
          'merge-static-orbit': { x: 1080, y: -60 },
          'static-vignette': { x: 1440, y: -60 },
          'static-grain': { x: 1800, y: -60 },
          __export__: { x: 2160, y: -60 },
        },
        mergeNodes: [{ id: 'merge-static-orbit', name: 'orbit over signal', blendMode: 'screen', opacity: 88 }],
        colorNodes: [],
      },
    ),
  },
  {
    id: 'paper-shards',
    name: 'Paper Shards',
    category: 'Texture study',
    summary: 'Paper fiber, cyanotype color, shard arrays, and type show how source nodes become a print system.',
    usedNodes: ['Fill', 'Noise', 'Array', 'Cyanotype', 'Riso Shift', 'Overprint'],
    startCopy: 'Start here when you want a procedural paper-and-shape composition.',
    doc: mkDoc(
      24002,
      '#110704',
      '4:5',
      [
        makeFillLayer({ id: 'paper-bg', name: 'warm plate', color: '#110704' }),
        noise('paper', 'paper-fiber', 'paper fiber', { opacity: 76 }),
        fx('cyanotype', 'blue print wash', { id: 'paper-cyan', cyanotype: 62 }),
        array('shardField', 'paper-shards', 'shard field', { color: '#fff4d6', accentColor: '#ff5a36', opacity: 86 }),
        fx('risoShift', 'loose registration', { id: 'paper-riso', risoShift: 16, risoAngle: 18 }),
        makeTextLayer({
          id: 'paper-title',
          name: 'caption',
          content: 'SOURCE\nFIRST',
          font: 'BEBAS',
          size: 78,
          color: '#fff7e8',
          x: 0.5,
          y: 0.58,
          scaleX: 1,
          scaleY: 1,
        }),
        fx('overprint', 'ink pressure', { id: 'paper-overprint', overprint: 28 }),
      ],
      {
        edges: [
          { id: 'e-paper-bg-fiber', fromId: 'paper-bg', fromPort: 'out', toId: 'paper-fiber', toPort: 'bg' },
          { id: 'e-paper-fiber-cyan', fromId: 'paper-fiber', fromPort: 'out', toId: 'paper-cyan', toPort: 'in' },
          { id: 'e-paper-shards-riso', fromId: 'paper-shards', fromPort: 'out', toId: 'paper-riso', toPort: 'in' },
          { id: 'e-paper-cyan-merge', fromId: 'paper-cyan', fromPort: 'out', toId: 'merge-paper-shards', toPort: 'a' },
          { id: 'e-paper-riso-merge', fromId: 'paper-riso', fromPort: 'out', toId: 'merge-paper-shards', toPort: 'b' },
          {
            id: 'e-paper-merge-title',
            fromId: 'merge-paper-shards',
            fromPort: 'out',
            toId: 'paper-title',
            toPort: 'bg',
          },
          {
            id: 'e-paper-title-overprint',
            fromId: 'paper-title',
            fromPort: 'out',
            toId: 'paper-overprint',
            toPort: 'in',
          },
          { id: 'e-paper-export', fromId: 'paper-overprint', fromPort: 'out', toId: '__export__', toPort: 'in' },
        ],
        positions: {
          'paper-bg': { x: -360, y: 120 },
          'paper-fiber': { x: 0, y: 120 },
          'paper-cyan': { x: 360, y: 120 },
          'paper-shards': { x: 0, y: -260 },
          'paper-riso': { x: 360, y: -260 },
          'merge-paper-shards': { x: 720, y: -80 },
          'paper-title': { x: 1080, y: -80 },
          'paper-overprint': { x: 1440, y: -80 },
          __export__: { x: 1800, y: -80 },
        },
        mergeNodes: [{ id: 'merge-paper-shards', name: 'paper plus shards', blendMode: 'screen', opacity: 72 }],
        colorNodes: [],
      },
    ),
  },
  {
    id: 'tower-type',
    name: 'Tower Type',
    category: 'Graph recipe',
    summary: 'A concrete texture branch and a warped title branch merge into a type-driven cover.',
    usedNodes: ['Noise', 'Duotone', 'Text', 'Wave', 'CA', 'Merge'],
    startCopy: 'Use this to study type as its own branch instead of a final flat layer.',
    doc: mkDoc(
      16300,
      '#050101',
      '1:1',
      [
        makeFillLayer({ id: 'tower-bg', name: 'black plate', color: '#050101' }),
        makeSourceLayer('noise', {
          id: 'tower-texture',
          name: 'concrete texture',
          color: '#250504',
          accentColor: '#9c1510',
          noiseType: 'cells',
          noiseScale: 46,
          noiseDetail: 5,
          noiseContrast: 70,
          noiseBalance: 42,
          opacity: 90,
          blendMode: 'screen',
        }),
        fx('duotone', 'red concrete', { id: 'tower-duotone', duotone: 82, duoA: '#050101', duoB: '#b32018' }),
        fx('vignette', 'stairwell falloff', { id: 'tower-vignette', vignette: 64 }),
        makeTextLayer({
          id: 'tower-title',
          name: 'title block',
          content: 'OG Buga\nFEARMUACH\n163ONMYCOCK\nHa Koprax',
          font: 'DISPLAY',
          size: 64,
          color: '#ffffff',
          x: 0.5,
          y: 0.47,
          rotation: -6,
          scaleX: 1.15,
          scaleY: 1.05,
        }),
        fx('wave', 'controlled warp', { id: 'tower-wave', waveAmt: 13, waveFreq: 2.2 }),
        fx('ca', 'white edge', { id: 'tower-ca', ca: 2 }),
        fx('scanlines', 'print lines', { id: 'tower-scan', scanlines: 8 }),
      ],
      {
        edges: [
          { id: 'e-tower-bg-texture', fromId: 'tower-bg', fromPort: 'out', toId: 'tower-texture', toPort: 'bg' },
          {
            id: 'e-tower-texture-duotone',
            fromId: 'tower-texture',
            fromPort: 'out',
            toId: 'tower-duotone',
            toPort: 'in',
          },
          {
            id: 'e-tower-duotone-vignette',
            fromId: 'tower-duotone',
            fromPort: 'out',
            toId: 'tower-vignette',
            toPort: 'in',
          },
          { id: 'e-tower-title-wave', fromId: 'tower-title', fromPort: 'out', toId: 'tower-wave', toPort: 'in' },
          { id: 'e-tower-wave-ca', fromId: 'tower-wave', fromPort: 'out', toId: 'tower-ca', toPort: 'in' },
          { id: 'e-tower-ca-scan', fromId: 'tower-ca', fromPort: 'out', toId: 'tower-scan', toPort: 'in' },
          { id: 'e-tower-bg-merge', fromId: 'tower-vignette', fromPort: 'out', toId: 'merge-tower-cover', toPort: 'a' },
          { id: 'e-tower-type-merge', fromId: 'tower-scan', fromPort: 'out', toId: 'merge-tower-cover', toPort: 'b' },
          { id: 'e-tower-export', fromId: 'merge-tower-cover', fromPort: 'out', toId: '__export__', toPort: 'in' },
        ],
        positions: {
          'tower-bg': { x: 0, y: 260 },
          'tower-texture': { x: 240, y: 260 },
          'tower-duotone': { x: 480, y: 260 },
          'tower-vignette': { x: 720, y: 260 },
          'tower-title': { x: 0, y: 0 },
          'tower-wave': { x: 240, y: 0 },
          'tower-ca': { x: 480, y: 0 },
          'tower-scan': { x: 720, y: 0 },
          'merge-tower-cover': { x: 980, y: 120 },
          __export__: { x: 1220, y: 120 },
        },
        mergeNodes: [{ id: 'merge-tower-cover', name: 'type over concrete', blendMode: 'normal', opacity: 100 }],
        colorNodes: [],
      },
    ),
  },
  {
    id: 'phantom-violet',
    name: 'Phantom Violet',
    category: 'Effect stack',
    summary: 'A dense emoji source becomes a ghosted cover through morph, warp, rays, grain, and bloom.',
    usedNodes: ['Emoji', 'Morph', 'Noise Warp', 'Rays', 'Grain', 'Bloom'],
    startCopy: 'Open this to inspect a classic layer effect stack and reduce or reorder passes.',
    doc: mkDoc(42069, '#0d0020', '1:1', [
      makeEmojiLayer({
        name: 'phantoms',
        emojis: ['👽', '💀', '✦', '🌀', '💜'],
        density: 32,
        minSz: 28,
        maxSz: 78,
        blur: 65,
      }),
      fx('morph', 'ghost drift', { morphAmt: 50, morphFreq: 7 }),
      fx('noiseWarp', 'signal bend', { noiseWarp: 30 }),
      fx('rays', 'violet rays', { rays: 18, rayInt: 68, rayColor: '#9900ff' }),
      fx('tint', 'violet wash', { tint: '#1a0035', tintOp: 25 }),
      fx('grain', 'dust', { grain: 25 }),
      fx('scanlines', 'scan', { scanlines: 15 }),
      fx('rgbSplit', 'split', { rgbSplit: 4 }),
      fx('vignette', 'falloff', { vignette: 40 }),
      fx('bloom', 'glow', { bloom: 25 }),
    ]),
  },
  {
    id: 'glitch-tape',
    name: 'Glitch Tape',
    category: 'Effect stack',
    summary: 'Video artifacts pile up through glitch, tear, mosh, interlace, split channels, and bloom.',
    usedNodes: ['Emoji', 'Glitch', 'Tear', 'Data Mosh', 'Interlace', 'RGB Split'],
    startCopy: 'Use this as a reference for VHS-style degradation without adding new nodes first.',
    doc: mkDoc(13370, '#001008', '16:9', [
      makeEmojiLayer({
        name: 'tape debris',
        emojis: ['📼', '🔴', '⚡', '💾', '🖥️'],
        density: 28,
        minSz: 20,
        maxSz: 90,
        blur: 50,
      }),
      fx('glitch', 'dropout', { glitch: 15 }),
      fx('tear', 'tracking tear', { tearAmt: 12, tearSize: 5 }),
      fx('dataMosh', 'mosh', { dataMosh: 60 }),
      fx('interlace', 'crt weave', { interlace: 40 }),
      fx('hueShift', 'green drift', { hueShift: 120 }),
      fx('rgbSplit', 'channel split', { rgbSplit: 18 }),
      fx('grain', 'video noise', { grain: 35 }),
      fx('scanlines', 'scan', { scanlines: 25 }),
      fx('tint', 'phosphor wash', { tint: '#002210', tintOp: 20 }),
      fx('vignette', 'frame darken', { vignette: 55 }),
      fx('bloom', 'tube bloom', { bloom: 35 }),
    ]),
  },
  {
    id: 'vortex-dream',
    name: 'Vortex Dream',
    category: 'Effect stack',
    summary: 'Orbital emoji scatter is pulled through vortex, barrel distortion, rays, hue, and bloom.',
    usedNodes: ['Emoji', 'Noise Warp', 'Vortex', 'Barrel', 'Rays', 'Bloom'],
    startCopy: 'Start from this when you want a vertical motion-poster feel from simple sources.',
    doc: mkDoc(77777, '#000820', '9:16', [
      makeEmojiLayer({
        name: 'orbitals',
        emojis: ['🌀', '🫧', '⭕', '💫', '🔵'],
        density: 45,
        minSz: 15,
        maxSz: 65,
        blur: 72,
      }),
      fx('noiseWarp', 'current', { noiseWarp: 20 }),
      fx('vortex', 'pull', { vortex: 80 }),
      fx('barrel', 'lens warp', { barrel: 60 }),
      fx('rays', 'blue rays', { rays: 24, rayInt: 55, rayColor: '#0066ff' }),
      fx('tint', 'blue wash', { tint: '#00082a', tintOp: 35 }),
      fx('hueShift', 'deep hue', { hueShift: 200 }),
      fx('rgbSplit', 'fringe', { rgbSplit: 7 }),
      fx('rgbSplit', 'split', { rgbSplit: 8 }),
      fx('vignette', 'falloff', { vignette: 65 }),
      fx('bloom', 'halo', { bloom: 55 }),
    ]),
  },
  {
    id: 'film-ghost',
    name: 'Film Ghost',
    category: 'Effect stack',
    summary: 'A film-burn stack uses heat warp, grain, interlace, vignette, and soft bloom for aged stock.',
    usedNodes: ['Emoji', 'Film Burn', 'Noise Warp', 'Grain', 'Interlace', 'Bloom'],
    startCopy: 'Open this to tune subtle versus destructive film aging controls.',
    doc: mkDoc(9876, '#140800', '4:5', [
      makeEmojiLayer({
        name: 'apparitions',
        emojis: ['🎞️', '👻', '🌫️', '✨', '🕯️'],
        density: 25,
        minSz: 40,
        maxSz: 100,
        blur: 80,
      }),
      fx('filmBurn', 'light leak', { filmBurn: 80 }),
      fx('noiseWarp', 'heat warp', { noiseWarp: 70 }),
      fx('barrel', 'soft warp', { barrel: 25 }),
      fx('rays', 'lamp flare', { rays: 6, rayInt: 40, rayColor: '#ff6600' }),
      fx('tint', 'amber wash', { tint: '#200a00', tintOp: 40 }),
      fx('grain', 'stock grain', { grain: 30 }),
      fx('interlace', 'aged scan', { interlace: 20 }),
      fx('vignette', 'fade', { vignette: 75 }),
      fx('bloom', 'soft bloom', { bloom: 45 }),
    ]),
  },
  {
    id: 'riso-print',
    name: 'Riso Print',
    category: 'Effect stack',
    summary: 'Duotone, posterize, halftone, registration shift, and grain create a print-shop finish.',
    usedNodes: ['Emoji', 'Duotone', 'Posterize', 'Halftone', 'Riso Shift', 'Grain'],
    startCopy: 'Use this to compare print effects that look similar but affect different parts of the image.',
    doc: mkDoc(31415, '#1a0010', '1:1', [
      makeEmojiLayer({
        name: 'petals',
        emojis: ['🌸', '📿', '🌺', '💌', '🎀'],
        density: 40,
        minSz: 25,
        maxSz: 75,
        blur: 45,
      }),
      fx('rays', 'pink flash', { rays: 12, rayInt: 60, rayColor: '#ff0080' }),
      fx('hueShift', 'ink hue', { hueShift: 310 }),
      fx('duotone', 'duo ink', { duotone: 70, duoA: '#0a001a', duoB: '#ff44cc' }),
      fx('posterize', 'plate bands', { posterize: 8 }),
      fx('halftone', 'screen dots', { halftone: 15 }),
      fx('risoShift', 'misregister', { risoShift: 16, risoAngle: 220 }),
      fx('grain', 'paper tooth', { grain: 30 }),
      fx('rgbSplit', 'registration split', { rgbSplit: 6 }),
      fx('vignette', 'edge fade', { vignette: 35 }),
      fx('bloom', 'ink glow', { bloom: 20 }),
    ]),
  },
  {
    id: 'acid-rain',
    name: 'Acid Rain',
    category: 'Effect stack',
    summary: 'A toxic palette is built from glitch, corrosion warp, mosh, rays, scanlines, and bloom.',
    usedNodes: ['Emoji', 'Glitch', 'Noise Warp', 'Data Mosh', 'Scanlines', 'Bloom'],
    startCopy: 'Open this when you want to learn how color drift and damage stack together.',
    doc: mkDoc(55555, '#0a1000', '16:9', [
      makeEmojiLayer({
        name: 'acid drops',
        emojis: ['☠️', '🧪', '💚', '⚗️', '🌿'],
        density: 38,
        minSz: 22,
        maxSz: 80,
        blur: 60,
      }),
      fx('glitch', 'dropout', { glitch: 10 }),
      fx('noiseWarp', 'corrosion warp', { noiseWarp: 40 }),
      fx('barrel', 'lens warp', { barrel: 30 }),
      fx('dataMosh', 'green smear', { dataMosh: 20 }),
      fx('rays', 'toxic rays', { rays: 16, rayInt: 52, rayColor: '#aaff00' }),
      fx('tint', 'sludge wash', { tint: '#091200', tintOp: 30 }),
      fx('hueShift', 'acid hue', { hueShift: 90 }),
      fx('rgbSplit', 'fringe', { rgbSplit: 6 }),
      fx('grain', 'grit', { grain: 28 }),
      fx('scanlines', 'signal rain', { scanlines: 18 }),
      fx('rgbSplit', 'channel bleed', { rgbSplit: 10 }),
      fx('vignette', 'edge rot', { vignette: 60 }),
      fx('bloom', 'neon spill', { bloom: 70 }),
    ]),
  },
  {
    id: 'void-echo',
    name: 'Void Echo',
    category: 'Effect stack',
    summary: 'Mirror, morph, vortex, duotone, interlace, and vignette turn a scatter into a dark echo.',
    usedNodes: ['Emoji', 'Mirror', 'Morph', 'Vortex', 'Duotone', 'Vignette'],
    startCopy: 'Use this to study repeating spatial effects before adding more content.',
    doc: mkDoc(11111, '#04000a', '9:16', [
      makeEmojiLayer({
        name: 'eclipses',
        emojis: ['🌑', '🌘', '⚫', '🖤', '🌙'],
        density: 50,
        minSz: 18,
        maxSz: 60,
        blur: 85,
      }),
      fx('mirror', 'echo mirror', { mirror: 2 }),
      fx('morph', 'slow drift', { morphAmt: 60, morphFreq: 4 }),
      fx('vortex', 'void pull', { vortex: 40 }),
      fx('rays', 'eclipse rays', { rays: 30, rayInt: 30, rayColor: '#6600aa' }),
      fx('tint', 'night wash', { tint: '#080010', tintOp: 50 }),
      fx('duotone', 'moon duo', { duotone: 30, duoA: '#02000a', duoB: '#8833ff' }),
      fx('interlace', 'echo lines', { interlace: 30 }),
      fx('hueShift', 'violet drift', { hueShift: 270 }),
      fx('grain', 'dust', { grain: 15 }),
      fx('rgbSplit', 'trace split', { rgbSplit: 2 }),
      fx('vignette', 'heavy falloff', { vignette: 85 }),
      fx('bloom', 'lunar bloom', { bloom: 60 }),
    ]),
  },
  {
    id: 'pixel-death',
    name: 'Pixel Death',
    category: 'Effect stack',
    summary:
      'Hard digital damage combines tear, mosh, whole-image low-res pixelate, posterize, duotone, and scanlines.',
    usedNodes: ['Emoji', 'Tear', 'Data Mosh', 'Pixelate', 'Posterize', 'Scanlines'],
    startCopy: 'Open this for a destructive effects pass where the order matters.',
    doc: mkDoc(66666, '#200000', '4:5', [
      makeEmojiLayer({
        name: 'wreckage',
        emojis: ['💀', '🔥', '⚡', '🩸', '☠️'],
        density: 35,
        minSz: 30,
        maxSz: 85,
        blur: 40,
      }),
      fx('tear', 'hard tear', { tearAmt: 8, tearSize: 4 }),
      fx('dataMosh', 'mosh', { dataMosh: 40 }),
      fx('interlace', 'shred', { interlace: 60 }),
      fx('pixelate', 'block crush', { pixelate: 6 }),
      fx('posterize', 'reduced bands', { posterize: 6 }),
      fx('duotone', 'blood duo', { duotone: 50, duoA: '#1a0000', duoB: '#ff4400' }),
      fx('rays', 'red spike', { rays: 10, rayInt: 70, rayColor: '#ff2200' }),
      fx('grain', 'grit', { grain: 30 }),
      fx('scanlines', 'scan', { scanlines: 30 }),
      fx('rgbSplit', 'fringe', { rgbSplit: 8 }),
      fx('rgbSplit', 'channel rip', { rgbSplit: 14 }),
      fx('vignette', 'edge crush', { vignette: 70 }),
      fx('bloom', 'burn', { bloom: 30 }),
    ]),
  },
];
