import {
  type CanvasDocument,
  type CanvasGraph,
  DEFAULT_EXPORT,
  makeEffectPresetLayer,
  makeFillLayer,
  makeImageLayer,
  makeSourceLayer,
  makeTextLayer,
} from '../types/config';

export interface StarterDocument {
  id: string;
  name: string;
  shortName: string;
  description: string;
  doc: CanvasDocument;
}

export const TEXTURE_TYPE_STACK_STARTER: StarterDocument = {
  id: 'layer-starter-texture-type',
  name: 'Texture Type Stack',
  shortName: 'Texture Type',
  description: 'A stack-only cover: fill, procedural texture, type, scanlines, and grain.',
  doc: {
    global: { bg: '#080407', seed: 87017, aspect: '1:1' },
    export: { ...DEFAULT_EXPORT },
    layers: [
      makeFillLayer({ id: 'starter-plate', name: 'ink plate', color: '#12051a' }),
      makeSourceLayer('noise', {
        id: 'starter-clouds',
        name: 'paper clouds',
        noiseType: 'clouds',
        noiseScale: 18,
        noiseDetail: 6,
        noiseContrast: 64,
        noiseBalance: 44,
        noiseWarp: 28,
        noiseTurbulence: 22,
        color: '#361423',
        accentColor: '#f06b4e',
        opacity: 88,
        blendMode: 'screen',
      }),
      makeTextLayer({
        id: 'starter-title',
        name: 'title',
        content: 'NOISE\nTYPE',
        font: 'DISPLAY',
        size: 132,
        color: '#f5ead8',
        x: 0.5,
        y: 0.53,
        rotation: -4,
        scaleX: 1.1,
        scaleY: 0.95,
      }),
      {
        ...makeEffectPresetLayer('risoShift', { value: 14 }),
        id: 'starter-registration',
        name: 'loose registration',
        risoAngle: 18,
      },
      {
        ...makeEffectPresetLayer('scanlines', { value: 12 }),
        id: 'starter-scanlines',
        name: 'print lines',
        scanlineWidth: 2,
      },
      {
        ...makeEffectPresetLayer('grain', { value: 18 }),
        id: 'starter-grain',
        name: 'paper tooth',
      },
    ],
  },
};

const SAMPLE_IMAGE = '/girl_image_landing.png';

export const MULTI_FONT_TYPE_STACK_STARTER: StarterDocument = {
  id: 'layer-starter-multi-font-type',
  name: 'Multi Font Type Stack',
  shortName: 'Multi Font',
  description: 'A stack-only cover for mixing poster title, mono subtitle, pixel label, credits, and print finish.',
  doc: {
    global: { bg: '#090504', seed: 87244, aspect: '4:5' },
    export: { ...DEFAULT_EXPORT },
    layers: [
      makeFillLayer({ id: 'multi-font-plate', name: 'warm plate', color: '#090504' }),
      makeImageLayer(SAMPLE_IMAGE, {
        id: 'multi-font-image',
        name: 'photo wash',
        fit: 'cover',
        opacity: 32,
        blendMode: 'normal',
        scaleX: 1.08,
        scaleY: 1.08,
      }),
      makeEffectPresetLayer('duotone', {
        id: 'multi-font-duotone',
        name: 'soft poster wash',
        value: 18,
        duoA: '#0c0504',
        duoB: '#9b4531',
      }),
      makeSourceLayer('noise', {
        id: 'multi-font-paper',
        name: 'paper tooth',
        noiseType: 'clouds',
        noiseScale: 22,
        noiseDetail: 5,
        noiseContrast: 58,
        noiseBalance: 45,
        noiseWarp: 18,
        noiseTurbulence: 16,
        color: '#220d08',
        accentColor: '#f2bc7a',
        opacity: 28,
        blendMode: 'screen',
      }),
      makeTextLayer({
        id: 'multi-font-title',
        name: 'poster title',
        content: 'TYPE\nMIX',
        font: 'BUNGEE',
        size: 116,
        color: '#fff1dc',
        x: 0.5,
        y: 0.39,
        rotation: -3,
        align: 'center',
        scaleX: 0.92,
        scaleY: 0.86,
      }),
      makeTextLayer({
        id: 'multi-font-subtitle',
        name: 'mono subtitle',
        content: 'ALPHA / PRINT / SOURCE',
        font: 'SPACE_MONO',
        size: 24,
        color: '#ff9b72',
        x: 0.5,
        y: 0.63,
        rotation: 0,
        align: 'center',
        scaleX: 1,
        scaleY: 1,
      }),
      makeTextLayer({
        id: 'multi-font-label',
        name: 'pixel label',
        content: 'V0.20',
        font: 'PRESS_START',
        size: 17,
        color: '#f6d8a8',
        x: 0.18,
        y: 0.18,
        rotation: -6,
        align: 'center',
        scaleX: 1,
        scaleY: 1,
      }),
      makeTextLayer({
        id: 'multi-font-credit',
        name: 'type credits',
        content: 'ARTIFACT\nFONT LIBRARY',
        font: 'SPECIAL',
        size: 21,
        color: '#ead6b8',
        x: 0.5,
        y: 0.84,
        rotation: 0,
        align: 'center',
        scaleX: 1,
        scaleY: 1,
      }),
      {
        ...makeEffectPresetLayer('risoShift', { value: 8 }),
        id: 'multi-font-registration',
        name: 'registration slip',
        risoAngle: 22,
      },
      {
        ...makeEffectPresetLayer('grain', { value: 14 }),
        id: 'multi-font-grain',
        name: 'print grain',
      },
    ],
  },
};

export const PHOTO_TYPE_STACK_STARTER: StarterDocument = {
  id: 'layer-starter-photo-type',
  name: 'Photo Type Stack',
  shortName: 'Photo Stack',
  description: 'A stack-only cover: image, duotone wash, big type, registration drift, and grain.',
  doc: {
    global: { bg: '#080607', seed: 87104, aspect: '4:5' },
    export: { ...DEFAULT_EXPORT },
    layers: [
      makeFillLayer({ id: 'photo-stack-plate', name: 'matte plate', color: '#080607' }),
      makeImageLayer(SAMPLE_IMAGE, {
        id: 'photo-stack-image',
        name: 'cover photo',
        fit: 'cover',
        opacity: 94,
        scaleX: 1.04,
        scaleY: 1.04,
      }),
      makeEffectPresetLayer('duotone', {
        id: 'photo-stack-duotone',
        name: 'warm duotone',
        value: 54,
        duoA: '#120b10',
        duoB: '#f07848',
      }),
      makeTextLayer({
        id: 'photo-stack-title',
        name: 'headline type',
        content: 'PHOTO\nTYPE',
        font: 'BEBAS',
        size: 118,
        color: '#f5ead8',
        x: 0.5,
        y: 0.66,
        rotation: -4,
        scaleX: 1.05,
      }),
      {
        ...makeEffectPresetLayer('risoShift', { value: 10 }),
        id: 'photo-stack-registration',
        name: 'type drift',
        risoAngle: 12,
      },
      {
        ...makeEffectPresetLayer('grain', { value: 18 }),
        id: 'photo-stack-grain',
        name: 'print grain',
      },
    ],
  },
};

export const NOISE_POSTER_STACK_STARTER: StarterDocument = {
  id: 'layer-starter-noise-poster',
  name: 'Noise Poster Stack',
  shortName: 'Noise Poster',
  description: 'A stack-only poster: fill, paper noise, oversized type, halftone, scanlines, and dust.',
  doc: {
    global: { bg: '#0b0504', seed: 87191, aspect: '1:1' },
    export: { ...DEFAULT_EXPORT },
    layers: [
      makeFillLayer({ id: 'noise-poster-plate', name: 'burnt plate', color: '#0b0504' }),
      makeSourceLayer('noise', {
        id: 'noise-poster-paper',
        name: 'paper static',
        noiseType: 'cells',
        noiseScale: 30,
        noiseDetail: 6,
        noiseContrast: 70,
        noiseBalance: 48,
        noiseWarp: 24,
        noiseTurbulence: 18,
        color: '#2b1209',
        accentColor: '#f4bb77',
        opacity: 84,
        blendMode: 'screen',
      }),
      makeTextLayer({
        id: 'noise-poster-title',
        name: 'poster type',
        content: 'NOISE\nPOSTER',
        font: 'DISPLAY',
        size: 118,
        color: '#f6e8c9',
        x: 0.5,
        y: 0.5,
        rotation: 3,
        scaleX: 1.05,
        scaleY: 0.96,
      }),
      makeEffectPresetLayer('halftone', {
        id: 'noise-poster-halftone',
        name: 'screen dots',
        value: 12,
      }),
      {
        ...makeEffectPresetLayer('scanlines', { value: 10 }),
        id: 'noise-poster-scanlines',
        name: 'print bands',
        scanlineWidth: 2,
      },
      {
        ...makeEffectPresetLayer('grain', { value: 24 }),
        id: 'noise-poster-grain',
        name: 'dust pass',
      },
    ],
  },
};

function recipeDoc(seed: number, bg: string, layers: CanvasDocument['layers'], graph: CanvasGraph): CanvasDocument {
  return {
    global: { bg, seed, aspect: '1:1' },
    export: { ...DEFAULT_EXPORT },
    layers,
    graph,
  };
}

export const PHOTO_TYPE_GRAPH_RECIPE: StarterDocument = {
  id: 'recipe-photo-type-graph',
  name: 'Photo Plus Type Recipe',
  shortName: 'Photo Type',
  description: 'A graph recipe that treats an image, color wash, title, and print grain as editable steps.',
  doc: recipeDoc(
    91201,
    '#070607',
    [
      makeFillLayer({ id: 'photo-base', name: 'matte plate', color: '#070607' }),
      makeImageLayer(SAMPLE_IMAGE, {
        id: 'photo-image',
        name: 'cover photo',
        fit: 'cover',
        opacity: 92,
        scaleX: 1.08,
        scaleY: 1.08,
      }),
      makeEffectPresetLayer('duotone', {
        id: 'photo-duotone',
        value: 58,
        duoA: '#151016',
        duoB: '#f07848',
      }),
      makeTextLayer({
        id: 'photo-title',
        name: 'headline type',
        content: 'AFTER\nIMAGE',
        font: 'BEBAS',
        size: 126,
        color: '#fff1dc',
        x: 0.5,
        y: 0.66,
        rotation: -3,
        scaleX: 1.04,
      }),
      makeEffectPresetLayer('grain', { id: 'photo-grain', name: 'paper grain', value: 16 }),
    ],
    {
      edges: [
        { id: 'e-photo-base-image', fromId: 'photo-base', fromPort: 'out', toId: 'photo-image', toPort: 'bg' },
        { id: 'e-photo-image-duotone', fromId: 'photo-image', fromPort: 'out', toId: 'photo-duotone', toPort: 'in' },
        { id: 'e-photo-duotone-title', fromId: 'photo-duotone', fromPort: 'out', toId: 'photo-title', toPort: 'bg' },
        { id: 'e-photo-title-grain', fromId: 'photo-title', fromPort: 'out', toId: 'photo-grain', toPort: 'in' },
        { id: 'e-photo-export', fromId: 'photo-grain', fromPort: 'out', toId: '__export__', toPort: 'in' },
      ],
      positions: {
        'photo-base': { x: -360, y: 60 },
        'photo-image': { x: 0, y: 60 },
        'photo-duotone': { x: 360, y: 60 },
        'photo-title': { x: 720, y: 60 },
        'photo-grain': { x: 1080, y: 60 },
        __export__: { x: 1440, y: 60 },
      },
      mergeNodes: [],
      colorNodes: [],
    },
  ),
};

export const STICKER_GRID_GRAPH_RECIPE: StarterDocument = {
  id: 'recipe-sticker-grid-graph',
  name: 'Sticker Grid Motif Recipe',
  shortName: 'Sticker Grid',
  description: 'A graph recipe for building a motif field, then placing type and registration effects over it.',
  doc: recipeDoc(
    91202,
    '#100607',
    [
      makeFillLayer({ id: 'sticker-base', name: 'ink plate', color: '#100607' }),
      makeSourceLayer('noise', {
        id: 'sticker-paper',
        name: 'paper noise',
        noiseType: 'clouds',
        noiseScale: 20,
        noiseDetail: 5,
        noiseContrast: 52,
        noiseWarp: 18,
        color: '#2a151b',
        accentColor: '#ff8f5c',
        opacity: 72,
        blendMode: 'screen',
      }),
      makeSourceLayer('array', {
        id: 'sticker-grid',
        name: 'sticker grid',
        arrayPattern: 'grid',
        arrayShape: 'diamond',
        arrayCount: 7,
        arrayRows: 6,
        arrayGap: 42,
        arraySize: 28,
        arrayJitter: 18,
        color: '#ffe6a3',
        accentColor: '#ff4f7a',
        opacity: 90,
        blendMode: 'screen',
      }),
      makeEffectPresetLayer('risoShift', {
        id: 'sticker-registration',
        name: 'loose registration',
        value: 16,
        risoAngle: 28,
      }),
      makeTextLayer({
        id: 'sticker-title',
        name: 'label type',
        content: 'GRID\nMOTIF',
        font: 'DISPLAY',
        size: 114,
        color: '#fff6dc',
        y: 0.5,
      }),
      makeEffectPresetLayer('overprint', { id: 'sticker-overprint', name: 'ink pressure', value: 22 }),
    ],
    {
      edges: [
        { id: 'e-sticker-base-paper', fromId: 'sticker-base', fromPort: 'out', toId: 'sticker-paper', toPort: 'bg' },
        { id: 'e-sticker-paper-grid', fromId: 'sticker-paper', fromPort: 'out', toId: 'sticker-grid', toPort: 'bg' },
        {
          id: 'e-sticker-grid-registration',
          fromId: 'sticker-grid',
          fromPort: 'out',
          toId: 'sticker-registration',
          toPort: 'in',
        },
        {
          id: 'e-sticker-registration-title',
          fromId: 'sticker-registration',
          fromPort: 'out',
          toId: 'sticker-title',
          toPort: 'bg',
        },
        {
          id: 'e-sticker-title-overprint',
          fromId: 'sticker-title',
          fromPort: 'out',
          toId: 'sticker-overprint',
          toPort: 'in',
        },
        { id: 'e-sticker-export', fromId: 'sticker-overprint', fromPort: 'out', toId: '__export__', toPort: 'in' },
      ],
      positions: {
        'sticker-base': { x: -360, y: 60 },
        'sticker-paper': { x: 0, y: 60 },
        'sticker-grid': { x: 360, y: 60 },
        'sticker-registration': { x: 720, y: 60 },
        'sticker-title': { x: 1080, y: 60 },
        'sticker-overprint': { x: 1440, y: 60 },
        __export__: { x: 1800, y: 60 },
      },
      mergeNodes: [],
      colorNodes: [],
    },
  ),
};

export const PRIMITIVE_IMAGE_GRAPH_RECIPE: StarterDocument = {
  id: 'recipe-primitive-image-graph',
  name: 'Primitive Over Image Recipe',
  shortName: 'Primitive Image',
  description: 'A graph recipe that merges a 3D primitive branch over an image branch before final print effects.',
  doc: recipeDoc(
    91203,
    '#030405',
    [
      makeFillLayer({ id: 'primitive-base', name: 'dark plate', color: '#030405' }),
      makeImageLayer(SAMPLE_IMAGE, {
        id: 'primitive-image',
        name: 'image branch',
        fit: 'cover',
        opacity: 74,
        blendMode: 'normal',
      }),
      makeEffectPresetLayer('cyanotype', { id: 'primitive-cyan', name: 'cool image wash', value: 52 }),
      makeSourceLayer('primitive', {
        id: 'primitive-shape',
        name: 'cover primitive',
        primitiveShape: 'cylinder',
        primitiveDepth: 72,
        primitiveShading: 'flat',
        tiltX: -12,
        tiltY: 34,
        tiltZ: -8,
        color: '#ff6a3a',
        accentColor: '#6ef0ff',
        opacity: 96,
      }),
      makeEffectPresetLayer('neonGlow', {
        id: 'primitive-glow',
        name: 'primitive halo',
        value: 36,
        neonColor: '#60f5ff',
      }),
      makeTextLayer({
        id: 'primitive-title',
        name: 'small type',
        content: 'OBJECT\nSTUDY',
        font: 'BEBAS',
        size: 72,
        color: '#f7f4df',
        y: 0.82,
      }),
      makeEffectPresetLayer('vignette', { id: 'primitive-vignette', name: 'frame falloff', value: 46 }),
    ],
    {
      edges: [
        {
          id: 'e-primitive-base-image',
          fromId: 'primitive-base',
          fromPort: 'out',
          toId: 'primitive-image',
          toPort: 'bg',
        },
        {
          id: 'e-primitive-image-cyan',
          fromId: 'primitive-image',
          fromPort: 'out',
          toId: 'primitive-cyan',
          toPort: 'in',
        },
        {
          id: 'e-primitive-shape-glow',
          fromId: 'primitive-shape',
          fromPort: 'out',
          toId: 'primitive-glow',
          toPort: 'in',
        },
        {
          id: 'e-primitive-cyan-merge',
          fromId: 'primitive-cyan',
          fromPort: 'out',
          toId: 'merge-primitive-image',
          toPort: 'a',
        },
        {
          id: 'e-primitive-glow-merge',
          fromId: 'primitive-glow',
          fromPort: 'out',
          toId: 'merge-primitive-image',
          toPort: 'b',
        },
        {
          id: 'e-primitive-merge-title',
          fromId: 'merge-primitive-image',
          fromPort: 'out',
          toId: 'primitive-title',
          toPort: 'bg',
        },
        {
          id: 'e-primitive-title-vignette',
          fromId: 'primitive-title',
          fromPort: 'out',
          toId: 'primitive-vignette',
          toPort: 'in',
        },
        { id: 'e-primitive-export', fromId: 'primitive-vignette', fromPort: 'out', toId: '__export__', toPort: 'in' },
      ],
      positions: {
        'primitive-base': { x: -360, y: 140 },
        'primitive-image': { x: 0, y: 140 },
        'primitive-cyan': { x: 360, y: 140 },
        'primitive-shape': { x: 0, y: -220 },
        'primitive-glow': { x: 360, y: -220 },
        'merge-primitive-image': { x: 720, y: -40 },
        'primitive-title': { x: 1080, y: -40 },
        'primitive-vignette': { x: 1440, y: -40 },
        __export__: { x: 1800, y: -40 },
      },
      mergeNodes: [{ id: 'merge-primitive-image', name: 'primitive over image', blendMode: 'screen', opacity: 92 }],
      colorNodes: [],
    },
  ),
};

export const PRINT_DAMAGE_GRAPH_RECIPE: StarterDocument = {
  id: 'recipe-print-damage-graph',
  name: 'Print Damage Poster Recipe',
  shortName: 'Print Damage',
  description: 'A graph recipe for pushing type through paper texture, halftone, tears, and final grain.',
  doc: recipeDoc(
    91204,
    '#0d0604',
    [
      makeFillLayer({ id: 'damage-base', name: 'aged plate', color: '#0d0604' }),
      makeSourceLayer('noise', {
        id: 'damage-paper',
        name: 'paper fiber',
        noiseType: 'cells',
        noiseScale: 34,
        noiseDetail: 6,
        noiseContrast: 68,
        noiseBalance: 46,
        noiseWarp: 36,
        noiseTurbulence: 24,
        color: '#25120a',
        accentColor: '#efc38a',
        opacity: 82,
        blendMode: 'screen',
      }),
      makeTextLayer({
        id: 'damage-title',
        name: 'poster type',
        content: 'PRINT\nDAMAGE',
        font: 'DISPLAY',
        size: 124,
        color: '#fff0cd',
        rotation: -5,
        scaleX: 1.08,
      }),
      makeEffectPresetLayer('halftone', { id: 'damage-halftone', name: 'screen dots', value: 14 }),
      makeEffectPresetLayer('tear', { id: 'damage-tear', name: 'paper tear', value: 10, tearSize: 5 }),
      makeEffectPresetLayer('grain', { id: 'damage-grain', name: 'dust pass', value: 28 }),
    ],
    {
      edges: [
        { id: 'e-damage-base-paper', fromId: 'damage-base', fromPort: 'out', toId: 'damage-paper', toPort: 'bg' },
        { id: 'e-damage-paper-title', fromId: 'damage-paper', fromPort: 'out', toId: 'damage-title', toPort: 'bg' },
        {
          id: 'e-damage-title-halftone',
          fromId: 'damage-title',
          fromPort: 'out',
          toId: 'damage-halftone',
          toPort: 'in',
        },
        { id: 'e-damage-halftone-tear', fromId: 'damage-halftone', fromPort: 'out', toId: 'damage-tear', toPort: 'in' },
        { id: 'e-damage-tear-grain', fromId: 'damage-tear', fromPort: 'out', toId: 'damage-grain', toPort: 'in' },
        { id: 'e-damage-export', fromId: 'damage-grain', fromPort: 'out', toId: '__export__', toPort: 'in' },
      ],
      positions: {
        'damage-base': { x: -360, y: 60 },
        'damage-paper': { x: 0, y: 60 },
        'damage-title': { x: 360, y: 60 },
        'damage-halftone': { x: 720, y: 60 },
        'damage-tear': { x: 1080, y: 60 },
        'damage-grain': { x: 1440, y: 60 },
        __export__: { x: 1800, y: 60 },
      },
      mergeNodes: [],
      colorNodes: [],
    },
  ),
};

export const LAYER_STARTER_DOCUMENTS: StarterDocument[] = [
  MULTI_FONT_TYPE_STACK_STARTER,
  TEXTURE_TYPE_STACK_STARTER,
  PHOTO_TYPE_STACK_STARTER,
  NOISE_POSTER_STACK_STARTER,
];
export const GRAPH_RECIPE_STARTER_DOCUMENTS: StarterDocument[] = [
  PHOTO_TYPE_GRAPH_RECIPE,
  STICKER_GRID_GRAPH_RECIPE,
  PRIMITIVE_IMAGE_GRAPH_RECIPE,
  PRINT_DAMAGE_GRAPH_RECIPE,
];
const STARTER_DOCUMENTS: StarterDocument[] = [...LAYER_STARTER_DOCUMENTS, ...GRAPH_RECIPE_STARTER_DOCUMENTS];

export function getStarterDocument(id: string): StarterDocument | undefined {
  return STARTER_DOCUMENTS.find((starter) => starter.id === id);
}
